version: '2'

services:
        mysql:
                image: mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=password
        fever:
                build: .
                links:
                        - mysql
                ports:
                        - 8080:80
