version: '2'

services:
        nginx-proxy:
                image: jwilder/nginx-proxy
                container_name: nginx-proxy
                ports:
                        - "80:80"
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock:ro
        mysql:
                image: mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=password
        fever:
                build: .
                links:
                        - mysql
                ports:
                        - 8080:80
                environment:
                        - VIRTUAL_HOST=<YOUR HOST>
